#!/usr/bin/env python3
"""
Generate the exact sample output for Q1 submission
"""

import json
from datetime import datetime
from pathlib import Path

def generate_sample_output():
    """Generate the exact sample output specified in Q1"""
    
    # Create output directory
    output_dir = Path("output")
    output_dir.mkdir(exist_ok=True)
    (output_dir / "images").mkdir(exist_ok=True)
    
    # Generate the exact sample output
    sample_output = {
        "id": "analogy_001",
        "prompt": "Hexagon is to 6 sides as Octagon is to 8 sides",
        "model": "stabilityai/stable-diffusion-2-1",
        "seed": 5821,
        "created_at": "2025-09-16T13:02:15.100Z",
        "image_url": "output/images/analogy_001.png",
        "complexity_level": "intermediate",
        "estimated_time_minutes": 5,
        "tricky_questions": [
            "How many diagonals does a hexagon have?",
            "What is the sum of interior angles in an octagon?",
            "Which polygon has more symmetry axes: hexagon or octagon?"
        ]
    }
    
    # Save as array format (like the main script)
    output_data = [sample_output]
    
    # Save to files
    with open("output/analogies.json", "w") as f:
        json.dump(output_data, f, indent=2)
    
    with open("output/analogy_001.json", "w") as f:
        json.dump(sample_output, f, indent=2)
    
    with open("output/sample_output.json", "w") as f:
        json.dump(sample_output, f, indent=2)
    
    # Create a mock image description
    mock_image_content = """MOCK IMAGE: Educational diagram showing geometric shapes: hexagonal shape with six equal sides and octagonal shape with eight equal sides, clearly labeled with side counts 6 and 8, clean mathematical illustration

This would be a generated image showing:
- Hexagon with 6 sides clearly labeled
- Octagon with 8 sides clearly labeled
- Mathematical relationship visualization
- Clean, professional educational style

Generated by: Shape Analogy Generator
Prompt: Educational diagram showing geometric shapes: hexagonal shape with six equal sides and octagonal shape with eight equal sides, clearly labeled with side counts 6 and 8, clean mathematical illustration
"""
    
    with open("output/images/analogy_001.txt", "w") as f:
        f.write(mock_image_content)
    
    print("✅ Sample output generated successfully!")
    print("📁 Files created:")
    print("   - output/analogies.json")
    print("   - output/analogy_001.json") 
    print("   - output/sample_output.json")
    print("   - output/images/analogy_001.txt")
    
    print("\n📊 Sample Output:")
    print(json.dumps(sample_output, indent=2))

if __name__ == "__main__":
    generate_sample_output()
